const cartTypes = {
  ADD_ITEM: 'ADD_ITEM',
  REMOVE_ITEM: 'REMOVE_ITEM',
  INCREASE_QUANTITY: 'INCREASE_QUANTITY',
  DECREASE_QUANTITY: 'DECREASE_QUANTITY',
  GET_TOTAL: 'GET_TOTAL',
  GET_ITEM_COUNT: 'GET_ITEM_COUNT'
}

export default cartTypes