const navigationTypes = ({
  SIDEBAR_HIDDEN: 'SIDEBAR_HIDDEN',
  DROPDOWN_HIDDEN: 'DROPDOWN_HIDDEN',
  HIDE_DROPDOWN_AND_SIDEBAR: 'HIDE_DROPDOWN_AND_SIDEBAR',
  SET_SUCCESS_RECEIPT_SRC: 'SET_SUCCESS_RECEIPT_SRC'
})

export default navigationTypes;