export const collectionTypes = ({
  ADD_ITEMS: 'ADD_ITEMS',
  GET_COLLECTION_START: 'GET_COLLECTION_START',
  GET_COLLECTION_SUCCESS: 'GET_COLLECTION_SUCCESS',
  GET_COLLECTION_FAILURE: 'GET_COLLECTION_FAILURE'
})